# Generated by Django 3.1.7 on 2021-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_frame', models.SmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
